### ISSUE TITLE
new version of fullwave2 GPU version??

### ISSUE THREAD

**Issue by hyeonjick** [gfpinton/fullwave_gpu#1]
Hello, I want to use fullwave2 simulation on GPU

I used GTX3080,ubuntu18.04, cuda 11.4 version..

Is there any update for the new cuda version??

**Comment by MasashiSode** [comment]
Thank you for contacting us.
In our environment we use either

- Operating System: Ubuntu 22.04
- CUDA driver version: 12.2
- CUDA toolkit version: 12.2
- GPU model: NVIDIA RTX 4090 GPU

or

- Operating System: Ubuntu 22.04
- CUDA driver version: 12.5
- CUDA toolkit version: 12.5
- GPU Model: NVIDIA RTX 3090 GPU

Could you try running the simulation with CUDA 12?

**Comment by MasashiSode** [comment]
@hyeonjick 
or could you try this binary first?
I think the binary in this `fullwave_gpu` repository is a bit old.

- https://github.com/pinton-lab/fullwave_python/blob/main/fullwave_simulation/bin/fullwave2_try6_nln_relaxing_pzero_rebuild3

**Comment by hyeonjick** [comment]
thank you!!!
